name: Generate and Upload Shorts

on:
  schedule:
    - cron: "0 8 * * *"  # Runs every day at 8 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python automate.py

      - name: Commit updated prompts.csv
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add prompts.csv
          git commit -m "Mark prompt as done"
          git push
